### ISSUE TITLE
[BUG] Type error trying to use plugin with Vite 5 and Rollup 4

### ISSUE THREAD

**Issue by DominicTulley** [janbiasi/rollup-plugin-sbom#263]
**Describe the bug**
I am trying to make use of this plugin (3.1.0) in a project which builds using vite V5 (5.4.14) and rollup 4 (4.34.8).
When I build, I get a type error 

```
vite.config.ts(7,29): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '({ mode }: ConfigEnv) => { plugins: (PluginOption[] | Plugin<any> | Plugin)[]; build: { minify: true; sourcemap: false; lib: { ...; }; target: string[]; }; esbuild: { ...; }; define: { ...; }; }' is not assignable to parameter of type 'UserConfigExport'.
      Type '({ mode }: ConfigEnv) => { plugins: (PluginOption[] | Plugin<any> | Plugin)[]; build: { minify: true; sourcemap: false; lib: { ...; }; target: string[]; }; esbuild: { ...; }; define: { ...; }; }' is not assignable to type 'UserConfigFnObject'.
        Call signature return types '{ plugins: (PluginOption[] | Plugin<any> | Plugin)[]; build: { minify: true; sourcemap: false; lib: { entry: string; name: string; fileName: (format: ModuleFormat) => string; }; target: string[]; }; esbuild: { ...; }; define: { ...; }; }' and 'UserConfig' are incompatible.
          The types of 'plugins' are incompatible between these types.
            Type '(PluginOption[] | Plugin<any> | Plugin)[]' is not assignable to type 'PluginOption[]'.
              Type 'PluginOption[] | Plugin<any> | Plugin' is not assignable to type 'PluginOption'.
                Type 'Plugin' is not assignable to type 'PluginOption'.
                  Type 'Plugin' is not assignable to type 'Plugin<any>'.
                    Types of property 'resolveId' are incompatible.
                      Type 'ObjectHook<(this: PluginContext, source: string, importer: string | undefined, options: { custom?: CustomPluginOptions | undefined; isEntry: boolean; }) => ResolveIdResult | Promise<...>, {}> | undefined' is not assignable to type 'ObjectHook<(this: PluginContext, source: string, importer: string | undefined, options: { attributes: Record<string, string>; custom?: CustomPluginOptions | undefined; ssr?: boolean | undefined; isEntry: boolean; }) => ResolveIdResult | Promise<...>> | undefined'.
                        Type '(this: PluginContext, source: string, importer: string | undefined, options: { custom?: CustomPluginOptions | undefined; isEntry: boolean; }) => ResolveIdResult | Promise<...>' is not assignable to type 'ObjectHook<(this: PluginContext, source: string, importer: string | undefined, options: { attributes: Record<string, string>; custom?: CustomPluginOptions | undefined; ssr?: boolean | undefined; isEntry: boolean; }) => ResolveIdResult | Promise<...>> | undefined'.
                          Type '(this: PluginContext, source: string, importer: string | undefined, options: { custom?: CustomPluginOptions | undefined; isEntry: boolean; }) => ResolveIdResult | Promise<...>' is not assignable to type '(this: PluginContext, source: string, importer: string | undefined, options: { attributes: Record<string, string>; custom?: CustomPluginOptions | undefined; ssr?: boolean | undefined; isEntry: boolean; }) => ResolveIdResult | Promise<...>'.
                            The 'this' types of each signature are incompatible.
                              Type 'PluginContext' is missing the following properties from type 'PluginContext': emitAsset, emitChunk, getAssetFileName, getChunkFileName, and 3 more.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
Simply attempting to build a project with these versions.
The vite config is
```
import { defineConfig } from "vite"
import react from "@vitejs/plugin-react"
import basicSsl from "@vitejs/plugin-basic-ssl";
import rollupPluginSbom from "rollup-plugin-sbom";

// https://vitejs.dev/config/
export default defineConfig(({ mode }) =>
{
  const env = { NODE_ENV: mode } // import.meta.env;

  return {
    plugins: [
  	  react({
        babel: {
          plugins: [
            [
              "babel-plugin-styled-components",
              {
                displayName: false,
                pure: true,
                minify: true,
                transpileTemplateLiterals: true,
              },
            ],
          ],
        },
      }),
      basicSsl(),
      rollupPluginSbom({})
    ],
...
```

**Expected behavior**
A clean bill with an sbom produced

**Environment (please complete the following information):**

- OS: macOS
- Runtime: Node/Yarn
- Version: Node 22, yarn 1.22.22

**Additional context**
I've read that the rollup Plugin interface changes occassionally and it seems to tend to break vite.  I've tried upgrading/downgrading vite, rollup and this plugin to try and get a matching set of versions with no luck.

**Comment by janbiasi** [comment]
Hi @DominicTulley thanks for the report. There are indeed a lot of cases where Vite breaks rollup types - often in combination with certain non-npm package managers. I'll try to reproduce the issue and identify the root cause for that. In general, I'd recommend to at least upgrade to a supported/maintained Vite version (v8 in this case), meanwhile you could try to use the [`rollupOptions`](https://github.com/janbiasi/rollup-plugin-sbom#usage-with-vite) instead and see if it still bricks the types. 

Worse case: you could suppress the type issue with `// @ts-expect-error` to at least get it building for now.

**Comment by DominicTulley** [comment]
Thanks for the quick response.
Using `rollupOptions` did not help (same error, slightly different stack trace).
I looked at upgrading to vite 8 - seems a lot of work as everything has changed!  I'll spend a bit more time on it though.
The `expect error` annotation allowed the build to run, as you suggested.  I guess there's no guarantee it's running correctly and producing a valid sbom though..

**Comment by janbiasi** [comment]
Just to note; `@ts-expect-error` just suppresses type errors, which is something completely different than _"not correctly producing a valid sbom"_. The plugin always generates a valid SBOM as long as the build succeeds. Producing the SBOM has nothing to do with TypeScript as it has nothing to do with the runtime behaviour of the plugin - it's just a static analysis tool for the interface (which as you mentions conflicts in your certain case). 

tl;dr you don't need to be afraid of generating an invalid SBOM at all :)

**Comment by DominicTulley** [comment]
Thanks @janbiasi , I did understand what what annotation was doing.  The reason we might worry about an invalid sbom being generated is that some js method invocation might not be done properly because the types don't match - and js is extremely good at just carrying on and doing "something" which might not be what was expected.

I failed to get your plugin working sadly, so I've revised my approach to use a different sbom generator (cdxgen).
It would have been cleaner to do it via the plugin so if you manage to pin this down and fix it, I may well be tempted to try again.

**Comment by janbiasi** [comment]
> that some js method invocation might not be done properly because the types don't match

I don't think that you fully understood what I commented above; TypeScript has no control over invocations at all, it makes no difference if i.E. the vite config is a JS file or a TS file - the execution is 1:1 the same. TypeScript gets transpiled to JavaScript before execution, so you will always just execute JavaScript - TS is not a runtime guard by any means.

> so if you manage to pin this down and fix it, I may well be tempted to try again

I just created a minimal reproduction for your case; only vite + react + sbom plugin in https://github.com/janbiasi/sbom-vite5-repro with a basic app (which you can checkout if you'd want to):
- There are no type issues at all
- SBOM was generated without warnings nor issues
- The [generated SBOM](https://github.com/janbiasi/sbom-vite5-repro/blob/main/dist/cyclonedx/bom.json) is 100% valid

So it seems like it's an issue in your project setup or combination with other plugins.
If you'd provide me a link to your code (if FOSS) or provide your exact setup as minimal reproducible repository (I don't need the application code) I could take a look at what your issue is - but the issue is certainly not this plugin 😃

**Comment by DominicTulley** [comment]
hmm, thanks for taking the time to reproduce the setup - unfortunate that it didn't exhibit the problem (from my perspective!).
It's not FOSS so I can't provide a link and I fear a minimal setup would be rather challenging to produce from it.

On the js/ts front - I fully understand how it works.  My point is that the ts type error tells us that some javascript code is going to expect an object in a certain form and the object being provided does not match that form. By ignoring the error we allow the javascript to run using that object but we don't know what the outcome will be - perhaps it won't read one of the properties from the object and so won't include some form of information, or won't filter the results in the way we want.

When I said this might result in an sbom that's not valid, I didn't mean to imply that it would be syntactically invalid but that it might not represent the end result of the analysis I think I'm requesting, but instead an analysis configured in a different way because of the mismatch in the object form being passed in to control the analysis.

Anyhow, thanks again for your effort in looking in to this.

**Comment by janbiasi** [comment]
> I can't provide a link and I fear a minimal setup would be rather challenging to produce from it.

You'd just need to provide:
- The full `plugins` list
- The version of the installed plugins

> By ignoring the error we allow the javascript to run using that object but we don't know what the outcome will be

This is a completely different thing, you could literally type an object as `RollupPlugin` and the compiler would just accept that, this is kind of a false assumed security in general.

>  might not represent the end result of the analysis I think I'm requesting

So what do you think you're requesting? The plugin works with Vite v5 and has a proof reproduction as well as a pretty large test suite (which I just noticed includes a test for Vite v5 as well - so the repro wasn't necessary, but this was my fault).

**Debug advice for your project**

I'd bet that another plugin pollutes your internal types and causes an issue with the augmentation. If you still don't want to provide the information above, I'd suggest that you debug the installed vite/rollup version in your module tree and override the causing resolution - as this will lead to more issues in general, far more of an issue than using `// @ts-expect-error` by the way.

Let me know if you'd want to provide me with the requested information for troubleshooting (also for other users). Feel free to close the issue on your behalf if you want to stop here :)

**Comment by DominicTulley** [comment]
Sorry @janbiasi I didn't mean to request anything additional from you.  It's clear that the problem is something local to my setup.
I'll go ahead and close this issue.
Thanks for your help.
